version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    network_mode: host
    env_file:
      - ./.env
    volumes:
      - ./server:/app/server
    environment:
      - TZ=America/Sao_Paulo